#
# Module manifest for module 'DevPilot.AgentHarness'
#
# Generated by: DevPilot Agents contributors
#
# Generated on: 8/1/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DevPilot.AgentHarness.psm1'

# Version number of this module.
ModuleVersion = '0.4.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '29d23743-703d-4eae-a4b6-37a17dcb38b0'

# Author of this module
Author = 'DevPilot Agents contributors'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) DevPilot Agents contributors. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Portable harness for autonomous, wrapper-governed coding agents driven by GitHub Copilot CLI. Provides fail-closed config loading, tool-ceiling enforcement, single-instance locking, atomic JSON state, strict result-marker parsing, an MCP client, and Copilot session discovery.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-DevPilotAgentPath', 'Resolve-AgentRepositoryRoot', 'Get-AgentSupportedModels', 'Get-AgentSessionIsolationEnvVars', 
               'Get-AgentHarnessCapabilityDescriptor', 'Assert-AgentDashboardLaunchAuthority',
               'Get-AgentWorkIqTargetUrl', 'Get-AgentMissingMcpServers', 
               'Get-AgentLaunchFailureReason', 'Remove-StaleAgentAttempts', 
               'Get-AgentCliJsonOutcome', 'Invoke-AgentWorkIqTool', 
               'Send-AgentTeamsChannelMessage', 'Send-AgentTeamsDirectMessage', 
               'Resolve-AgentTeamsUserChatId', 'New-AgentTeamsMessageHtml', 
               'Get-AgentRequiredProperty', 'Get-AgentDefaultModelSentinel', 
               'Assert-AgentSupportedModel', 'Test-ParserValidity', 
               'Get-OnceFinalExitCode', 'Test-StrictJsonInt', 'New-AgentNonce', 
               'New-AgentPipeName',
               'Test-AgentValidatedParamRebind', 
               'Test-AgentInteractiveOutput', 'New-AgentOutputContext', 'Set-AgentOutputRepositoryIdentity', 'Set-AgentOutputLegacySuppression',
               'Get-AgentNormalizedSkipReason', 'Format-AgentCount',
               'Format-AgentSkipSummary', 'Publish-AgentEvent', 'Close-AgentOutputContext',
               'Test-AgentProtectedBranch', 'Get-AgentConfigProperty', 
               'Get-AgentConfigString', 'Get-AgentConfigInt', 'Get-AgentConfigBool', 
               'Get-AgentConfigObject', 'Get-AgentConfigStringArray', 
               'Get-AgentConfig', 'Test-AgentAllowToolCeiling', 
               'Get-AgentCopilotArgs', 'Enter-AgentLock', 'Exit-AgentLock', 
               'Get-AgentSha256', 'Get-AgentDefaultDurableStateRoot', 'Get-AgentDefaultLeaseRoot', 'Get-AgentDefaultWatchStateRoot',
               'Test-AgentPathWithin', 'Resolve-AgentTrustedRoot', 'Assert-AgentTrustedFile', 'Remove-AgentContainedDirectory', 'Get-AgentRepositoryIdentityKey', 'Get-AgentExecutionKey',
               'Enter-AgentWorkLease', 'Get-AgentDurableStateContext', 'Enter-AgentDurableStateLock',
               'Invoke-AgentWithWorkAuthority', 'Enter-AgentManualDispatchStartup', 'Get-AgentManualOperatorContext',                'Test-AgentManualCancellationRequested', 'Get-AgentCancellationOutcome',
               'Exit-AgentManualDispatchAuthority',
               'Get-AgentDefaultCapabilityOverrideRoot', 'ConvertTo-AgentCanonicalEpochSeconds', 'Get-AgentWorktreeIdentity',
               'Read-AgentStableFile', 'ConvertFrom-AgentTrustedCapabilityJson', 'Resolve-AgentEffectiveCapabilitySettings',
               'Resolve-AgentCapabilityPolicyPartition', 'Enter-AgentCapabilityOverrideLock',
               'Get-AgentDefaultCapabilityOverrideKillSwitchRoot', 'Test-AgentCapabilityOverrideKillSwitch',
               'Enable-AgentCapabilityOverrideKillSwitch', 'Disable-AgentCapabilityOverrideKillSwitch',
               'Get-AgentCapabilityOverrideKillSwitchExpiresAtUtc',
               'Set-AgentCapabilityOverrideSetting',
               'Get-AgentDelegationPolicyPath', 'Get-AgentDelegationPolicy', 'Test-AgentDelegationAllows',
               'Get-AgentDelegationPolicyOrNull', 'Get-AgentDelegationPolicyOrThrow',
               'Get-AgentWideningGrantArtifactPath', 'New-AgentWideningGrantArtifact', 'Get-AgentWideningGrantArtifact',
               'Remove-AgentWideningGrantArtifact', 'New-AgentWideningChallenge', 'Test-AgentWideningChallengeShape',
               'Test-AgentAutoCompleteGrantWouldBeNoOp', 'Resolve-AgentWideningEffectiveDiff',
               'New-AgentBrokerAttestationSecret', 'Get-AgentAttestationDigest', 'Get-AgentAttestationProof',
               'Receive-AgentBrokerAttestationSecret', 'Assert-AgentManualDispatchEarlyContext',
               'ConvertFrom-AgentProcStatPpid', 'Get-AgentImmediateParentProcessId', 'Get-AgentProcessCommandLine',
               'ConvertFrom-AgentWindowsCommandLineArgv', 'Get-AgentProcessArgv', 'Assert-AgentBrokerCommandLineShape',
               'Assert-AgentBrokerProcessAnchor',
               'Assert-AgentDashboardCommandLineShape', 'Test-AgentDashboardLaunchProvenance',
               'Repair-AgentDurableState', 'Read-AgentDurableState', 'Write-AgentDurableState',
               'Get-AgentDurableRecords', 'Get-AgentDurableRecordsSnapshot', 'Set-AgentDurableRecords', 'Initialize-AgentDurableState',
               'Test-AgentAnalysisRequired', 'Test-AgentReviewerDeliveryPending', 'Confirm-AgentLegacyRecordsForMigration',
               'Get-JsonState', 'Set-JsonState', 'Write-AgentMetadata', 
               'ConvertFrom-AgentResultMarker', 'Find-CopilotSessionForBranch', 
               'Set-TimedProcessArguments', 'Stop-ProcessTree', 
               'Resolve-AgentPwshPath', 'ConvertTo-AgentCanonicalJson', 'Get-AgentCanonicalDigest',
               'Test-AgentOperatorPrompt', 'New-AgentRedirectedProcess', 'New-AgentPersistentRedirectedProcess', 'Complete-AgentRedirectedProcess',
               'Get-AgentProcessStartIdentity', 'New-AgentProcessContainment', 'Stop-AgentProcessContainment', 'Test-AgentProcessContainmentExited', 'Close-AgentProcessContainment',
               'Get-TaskTextBeforeDeadline', 'Invoke-TimedProcess', 
               'Open-AgentMcpSession', 'Close-AgentMcpSession', 
               'Send-AgentMcpRequest', 'Send-AgentMcpNotification', 
               'Invoke-AgentMcpTool',
    'Get-AgentSupportedProvider', 'Test-AgentProviderSupported', 'New-AgentProviderContext', 'Assert-AgentProviderContext',
    'New-AgentUnverifiedRepositoryIdentity', 'Resolve-AgentProviderRepositoryIdentity',
    'Invoke-AgentGitHubApi', 'Invoke-AgentGitHubGraphQl', 'ConvertTo-AgentProviderPullRequestStatus', 'ConvertTo-AgentProviderVote',
    'ConvertTo-AgentProviderSnapshot', 'ConvertTo-AgentProviderThreadStatus', 'Get-AgentProviderPullRequestSnapshot',
    'Get-AgentProviderActivePullRequestIds', 'Get-AgentProviderCommitDateUtc', 'Get-AgentProviderPullRequestThreads',
    'Get-AgentProviderValidationRun', 'Set-AgentProviderPullRequestVote'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'copilot', 'agents', 'automation', 'devops', 'powershell', 'ai'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/joerob-msft/devpilot-agents/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/joerob-msft/devpilot-agents'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial extraction from an in-repo prototype. Harness is provider-agnostic; agent wrappers currently target Azure DevOps.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
