#!/usr/bin/env pwsh
#requires -Version 7.0
<#
.SYNOPSIS
    Evaluates a signed private canary read-only, without posting or running a model.
.DESCRIPTION
    Default-off. Accepts only the ACL-private external root generated by
    Invoke-PrivateCanarySignedIntake.ps1. Requires fresh source and head checks.
    Candidate-only results cannot authorize delivery.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$StateRoot,
    [string]$SourceSelectorPath,
    [string]$SourceSelectorKeyPath,
    [string]$MergedPinPath,
    [string]$MergedPinKeyPath,
    [string]$AzureCliPath = 'az',
    [ValidateSet('FourRule', 'CoverageOnly')][string]$Mode = 'FourRule',
    [switch]$Run
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
Import-Module (Join-Path $repo 'src\DevPilot.ActivePrCanary\DevPilot.ActivePrCanary.psm1')
Import-Module (Join-Path $repo 'src\DevPilot.ActivePrCanary\DevPilot.PrivateCanaryRunner.psd1')
$source = if ($Run) {
    Read-CanaryPrivateSourceSelector -SelectorPath $SourceSelectorPath `
        -KeyPath $SourceSelectorKeyPath -RepositoryRoot $repo
} else { @{ selector = $null; key = $null } }
$merged = if ($Run) {
    Read-CanaryPrivateMergedPin -PinPath $MergedPinPath `
        -KeyPath $MergedPinKeyPath -RepositoryRoot $repo `
        -SourceSelector $source.selector
} else { @{ envelope = $null; key = $null } }
Invoke-PrivateCanaryEvaluation -StateRoot $StateRoot -RepositoryRoot $repo `
    -SourceSelector $source.selector -SourceSelectorKey $source.key `
    -MergedPinEnvelope $merged.envelope -MergedPinKey $merged.key `
    -AzureCliPath $AzureCliPath -Mode $Mode -Run:$Run | ConvertTo-Json -Depth 16
