#!/usr/bin/env pwsh
#requires -Version 7.0
<#
.SYNOPSIS
    Evaluates a signed private canary read-only, without posting or running a model.
.DESCRIPTION
    Default-off. Accepts only the ACL-private external root generated by
    Invoke-PrivateCanarySignedIntake.ps1. Requires fresh source and head checks.
    Candidate-only results cannot authorize delivery.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$StateRoot,
    [string]$AzureCliPath = 'az',
    [switch]$Run
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
Import-Module (Join-Path $repo 'src\DevPilot.ActivePrCanary\DevPilot.PrivateCanaryRunner.psd1')
Invoke-PrivateCanaryEvaluation -StateRoot $StateRoot -RepositoryRoot $repo `
    -AzureCliPath $AzureCliPath -Run:$Run | ConvertTo-Json -Depth 16
